plugins {
    id 'eclipse'
    id 'idea'
    id 'war'
}

apply plugin: "org.apache.grails.gradle.grails-web"
apply plugin: "org.apache.grails.gradle.grails-gsp"
apply plugin: 'cloud.wondrify.asset-pipeline'

assets {
    minifyJs = true
    minifyCss = true
}

configurations {
    developmentOnly
    runtimeClasspath {
        extendsFrom developmentOnly
    }
}

grails {
    plugins {
        implementation project(':grails-markdown')
    }
}

dependencies {
    developmentOnly("org.springframework.boot:spring-boot-devtools")
    
    // Spring dependencies
    implementation "org.springframework.boot:spring-boot-starter-logging"
    implementation "org.springframework.boot:spring-boot-starter-validation"
    implementation "org.springframework.boot:spring-boot-autoconfigure"
    implementation "org.springframework.boot:spring-boot-starter-tomcat"

    // Grails Dependencies
    implementation "org.apache.grails:grails-web-boot"
    implementation "org.apache.grails:grails-logging"
    implementation "org.apache.grails:grails-rest-transforms"
    implementation "org.apache.grails:grails-databinding"
    implementation "org.apache.grails.i18n:grails-i18n"
    implementation "org.apache.grails:grails-services"
    implementation "org.apache.grails:grails-url-mappings"
    implementation "org.apache.grails:grails-interceptors"
    implementation "org.apache.grails:grails-gsp"
    implementation "org.apache.grails:grails-layout"

    // Database
    implementation "org.apache.grails:grails-data-hibernate5"

    // H2 Database
    runtimeOnly "com.h2database:h2"

    // asset pipeline
    runtimeOnly "cloud.wondrify:asset-pipeline-grails"
}

// https://github.com/apache/grails-core/issues/15321
tasks.withType(GroovyCompile).configureEach {
    groovyOptions.optimizationOptions.indy = false
}
