buildscript {
    repositories {
        maven {
            url = 'https://repository.apache.org/content/groups/snapshots'
            content {
                includeVersionByRegex 'org[.]apache[.]((grails)|(groovy)).*', '.*', '.*-SNAPSHOT'
            }
        }
        maven {
            url = 'https://central.sonatype.com/repository/maven-snapshots'
            content {
                includeVersionByRegex 'cloud[.]wondrify', '.*', '.*-SNAPSHOT'
            }
        }
        maven { url = 'https://repo.grails.org/grails/restricted' }
    }
    dependencies {
        classpath platform("org.apache.grails:grails-bom:$grailsVersion")
        classpath 'org.apache.grails:grails-gradle-plugins'
        classpath 'org.apache.grails.gradle:grails-publish'
        classpath 'cloud.wondrify:asset-pipeline-gradle'
    }
}

// Define this in ~/.gradle/gradle.properties
ext {
    useMavenLocal = project.findProperty('useMavenLocal') ?: false
}

allprojects {
    repositories {
        mavenCentral()

        maven {
            url = 'https://repository.apache.org/content/groups/snapshots'
            content {
                includeVersionByRegex 'org[.]apache[.]((grails)|(groovy)).*', '.*', '.*-SNAPSHOT'
            }
        }

        maven { url = 'https://repo.grails.org/grails/restricted' }

        if (useMavenLocal) {
            mavenLocal()
        }
    }
}

version = projectVersion
group = "org.grails.plugins"

subprojects { Project project ->
    project.version = projectVersion
    project.group = rootProject.group

    tasks.withType(Test).configureEach {
        useJUnitPlatform()

        testLogging {
            showStandardStreams = true
            exceptionFormat = 'full'
        }
    }

    if (project.name.endsWith('grails-markdown')) {
        apply plugin: "org.apache.grails.gradle.grails-publish"
        grailsPublish {
            githubSlug = 'grails-plugins/grails-markdown'
            license {
                name = 'Apache-2.0'
            }
            title = "Grails Markdown Plugin"
            desc = "Grails Markdown Plugin for Grails 7+"
            developers = [
                    robertoschwald: "Robert Oschwald",
                    longwa        : "Aaron Long",
                    elkr          : "Elmar Kretzer",
                    jamesfredley  : "James Fredley",
                    jdaugherty    : "James Daugherty",
                    rahulshishodia: "Rahul Shishodia",
                    sbglasius     : "Søren Berg Glasius"
            ]
            websiteUrl = "https://github.com/grails-plugins/grails-markdown"
            issueTrackerUrl = "https://github.com/grails-plugins/grails-markdown/issues"
            vcsUrl = "https://github.com/grails-plugins/grails-markdown"
        }
    }
}
