buildscript {
    repositories {
        maven {
            url = 'https://repository.apache.org/content/groups/snapshots'
            content {
                includeVersionByRegex 'org[.]apache[.]((grails)|(groovy)).*', '.*', '.*-SNAPSHOT'
            }
        }
        maven { url = 'https://repo.grails.org/grails/restricted' }
    }
    dependencies {
        classpath platform("org.apache.grails:grails-bom:$grailsVersion")
        classpath "org.apache.grails:grails-gradle-plugins"
    }
}

plugins {
    id "java-library"
    id "idea"
    id "eclipse"
    id "maven-publish"
}

apply plugin: 'org.apache.grails.gradle.grails-plugin'
apply plugin: "org.apache.grails.gradle.grails-publish"

// Define this in ~/.gradle/gradle.properties
ext {
    useMavenLocal = project.findProperty('useMavenLocal') ?: false
}

allprojects {
    repositories {
        mavenCentral()

        maven {
            url = 'https://repository.apache.org/content/groups/snapshots'
            content {
                includeVersionByRegex 'org[.]apache[.]((grails)|(groovy)).*', '.*', '.*-SNAPSHOT'
            }
        }

        maven { url = 'https://repo.grails.org/grails/restricted' }

        if (useMavenLocal) {
            mavenLocal()
        }
    }
}

version projectVersion
group 'org.apache.grails'

compileJava.options.release = 17

dependencies {
    implementation platform("org.apache.grails:grails-bom:$grailsVersion")
    compileOnly 'org.apache.grails:grails-core'
    compileOnly 'org.apache.grails.views:grails-web-taglib'

    implementation 'com.vladsch.flexmark:flexmark-all:0.64.8'

    console 'org.apache.grails:grails-console'

    testImplementation 'org.apache.grails:grails-testing-support-web'
    testImplementation "org.spockframework:spock-core"
}

tasks.withType(Test).configureEach {
    useJUnitPlatform()

    testLogging {
        showStandardStreams = true
        exceptionFormat = 'full'
    }
}

grailsPublish {
    githubSlug = 'grails-plugins/grails-markdown'
    license {
        name = 'Apache-2.0'
    }
    title = "Grails Markdown Plugin"
    desc = "Grails Markdown Plugin for Grails 7+"
    developers = [
            robertoschwald: "Robert Oschwald",
            longwa        : "Aaron Long",
            elkr          : "Elmar Kretzer",
            jamesfredley  : "James Fredley",
            jdaugherty    : "James Daugherty",
            rahulshishodia: "Rahul Shishodia"
    ]
    websiteUrl = "https://github.com/grails-plugins/grails-markdown"
    issueTrackerUrl = "https://github.com/grails-plugins/grails-markdown/issues"
    vcsUrl = "https://github.com/grails-plugins/grails-markdown"
}

bootJar.enabled = false

grails {
    springDependencyManagement = false
}
